# example docker-compose configuration file for using mkodockx/docker-clamav
version: "3"

services:
  av:
    image: mkodockx/docker-clamav
    container_name: nextav
    networks:
      - backend

  app:
    image: nextcloud:fpm-alpine
    container_name: nextapp
    restart: always
    env_file:
      - env/app.env
    volumes:
      - html:/var/www/html
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    depends_on: 
      - av
      - db
      - redis
    networks:
      outpost_network:
      default:
      
  db:
    image: mariadb
    container_name: nextdb
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    env_file:
      - env/db.env

  redis:
    image: redis:alpine
    container_name: nextredis
    restart: unless-stopped

volumes:
  html:
  db:
  clam:

networks:
  outpost_network:
    external: true
